### ISSUE TITLE
Add lost connection handling

### ISSUE THREAD

**Issue by bsoyka** [bsoyka/brainbot#5]
**Is your feature request related to a problem? Please describe.**
Whenever the device running the bot loses internet connection for just a moment, it starts sending many error messages per second until the program is manually restarted. (https://bsoyka.is-ne.at/8rMboJ.png)

**Describe the solution you'd like**
For now, I believe the easiest way to handle this would be to make the live session close on loss of connection. Hopefully it's as simple as adding this to the live session code:

```py
@session.on_connection_loss
async def on_connection_loss():
    await session.close()
```

**Describe alternatives you've considered**
It would be neat to have the bot automatically attempt to reconnect, but I'm not sure if that's possible. For now, let's just stick with closing the session.

**Comment by LukeG294** [comment]
I'll take this one 👍
